<?
$PERM["bitrix"]["9"]="R";
$PERM["bitrix"]["8"]="R";
$PERM["bitrix"]["10"]="R";
$PERM["/"]["9"]="W";
$PERM["/"]["8"]="W";
$PERM["/"]["10"]="W";
$PERM["/"]["*"]="R";
$PERM["en"]["G6"]="X";
$PERM["en"]["G7"]="X";
$PERM["personal"]["7"]="W";
$PERM["catalog"]["7"]="W";
$PERM["news"]["7"]="W";
$PERM["about"]["7"]="W";
$PERM["index.php"]["7"]="W";
?>